// Mocks generated by Mockito 5.0.7 from annotations
// in estaciona_mais/test/app/features/home/data/repositories/dashboard_repository_impl_test.dart.
// Do not manually edit this file.

import 'package:estaciona_mais/app/features/home/data/datasources/dashboard_datasource.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [DashboardDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockDashboardDataSource extends _i1.Mock
    implements _i2.DashboardDataSource {
  MockDashboardDataSource() {
    _i1.throwOnMissingStub(this);
  }
}
