// Mocks generated by Mockito 5.0.7 from annotations
// in estaciona_mais/test/app/features/extract/data/repositories/extract_repository_impl_test.dart.
// Do not manually edit this file.

import 'package:estaciona_mais/app/features/extract/data/datasources/extract_datasource.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [ExtractDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockExtractDataSource extends _i1.Mock implements _i2.ExtractDataSource {
  MockExtractDataSource() {
    _i1.throwOnMissingStub(this);
  }
}
