// Mocks generated by Mockito 5.0.7 from annotations
// in estaciona_mais/test/app/features/space_management/domain/usecases/space_management_repository_mock.dart.
// Do not manually edit this file.

import 'package:estaciona_mais/app/features/space_management/domain/repositories/space_management_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

// ignore_for_file: prefer_const_constructors

// ignore_for_file: avoid_redundant_argument_values

/// A class which mocks [SpaceManagementRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpaceManagementRepository extends _i1.Mock
    implements _i2.SpaceManagementRepository {
  MockSpaceManagementRepository() {
    _i1.throwOnMissingStub(this);
  }
}
